name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23.2
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.2"
        id: go
      - run: |
          go get modernc.org/libc@v1.61.0
          go get modernc.org/sqlite@v1.33.1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          clean: false
          submodules: "recursive"
      - run: |
          git fetch --prune --unshallow --tags

      - name: Build and Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
